In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import torch.nn as nn
import torch.functional as F
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from plotly.subplots import make_subplots
import cufflinks as cf
cf.go_offline()
%matplotlib inline

In [2]:
df = pd.read_csv('GujAE.csv')
df1 = pd.read_csv('gujarat_AC.csv')

In [3]:
df1.columns

Index(['ac_name', 'ac_no', 'dist_name', 'dt_code', 'pc_id', 'pc_name', 'pc_no',
       'st_code', 'st_name'],
      dtype='object')

In [28]:
df1

,ac_name,ac_no,dist_name,dt_code,pc_id,pc_name,pc_no,st_code,st_name
0,NaN,0,KACHCHH,1,2400,NaN,0,24,GUJARAT
1,Vejalpur,42,AHMADABAD,7,2406,GANDHINAGAR,6,24,GUJARAT
2,Jamnagar South,79,JAMNAGAR,10,2412,JAMNAGAR,12,24,GUJARAT
3,Manjalpur,145,VADODARA,19,2420,VADODARA,20,24,GUJARAT
4,Bhavnagar West,105,BHAVNAGAR,14,2415,BHAVNAGAR,15,24,GUJARAT
...,...,...,...,...,...,...,...,...,...
183,Gandevi (ST),176,NAVSARI *,24,2425,NAVSARI,25,24,GUJARAT
184,Dharampur,178,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT
185,Pardi,180,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT
186,Kaprada (ST),181,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT
187,Umbergaon,182,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT

In [4]:
df.columns

Index(['Election_Type', 'State_Name', 'Assembly_No', 'Constituency_No', 'Year',
       'month', 'Poll_No', 'DelimID', 'Position', 'Candidate', 'Sex', 'Party',
       'Votes', 'Candidate_Type', 'Valid_Votes', 'Electors',
       'Constituency_Name', 'Constituency_Type', 'Sub_Region', 'N_Cand',
       'Turnout_Percentage', 'Vote_Share_Percentage', 'Deposit_Lost', 'Margin',
       'Margin_Percentage', 'ENOP', 'pid', 'Party_Type_TCPD', 'Party_ID',
       'last_poll', 'Contested', 'Last_Party', 'Last_Party_ID',
       'Last_Constituency_Name', 'Same_Constituency', 'Same_Party', 'No_Terms',
       'Turncoat', 'Incumbent', 'Recontest', 'Age', 'District_Name', 'PC_Name',
       'PC_No', 'CandID', 'MyNeta_education', 'TCPD_Prof_Main',
       'TCPD_Prof_Main_Desc', 'TCPD_Prof_Second', 'TCPD_Prof_Second_Desc'],
      dtype='object')

In [5]:
df.rename(columns={'Constituency_No':'ac_no'}, inplace=True)

In [6]:
final_df = pd.merge(df, df1, on="ac_no", how='inner')

In [7]:
final_df

,Election_Type,State_Name,Assembly_No,ac_no,Year,month,Poll_No,DelimID,Position,Candidate,...,TCPD_Prof_Second,TCPD_Prof_Second_Desc,ac_name,dist_name,dt_code,pc_id,pc_name,pc_no,st_code,st_name
0,AE,Gujarat,11,1,2007,12,0,3,1,JAYANTILAL PARSOTTAM BHANUSHALI,...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
1,AE,Gujarat,11,1,2007,12,0,3,2,JADEJA NARENDRASINH MADHAVSINHJI,...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
2,AE,Gujarat,11,1,2007,12,0,3,3,HALEPOTRA IBRAHIM JAFAR,...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
3,AE,Gujarat,11,1,2007,12,0,3,4,BHAVANI HANSRAJBHAI PARBATBHAI,...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
4,AE,Gujarat,11,1,2007,12,0,3,5,KULINKANT BHOJRAJ SHAH (LODAYA),...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5247,AE,Gujarat,13,182,2017,12,0,4,4,BOCHAL HASMUKHBHAI RAMANBHAI,...,Agriculture,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT
5248,AE,Gujarat,13,182,2017,12,0,4,5,SHAILESHBHAI UKADBHAI DABHADIA,...,NaN,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT
5249,AE,Gujarat,13,182,2017,12,0,4,6,NARESHBHAI UKKADBHAI OZARIYA,...,NaN,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT
5250,AE,Gujarat,13,182,2017,12,0,4,7,VADIYA LAXMANBHAI CHHAGANBHAI,...,NaN,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT
5251,AE,Gujarat,13,182,2017,12,0,4,8,GOVINDBHAI VESTABHAI PATEL,...,NaN,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT

In [8]:
def win(x):
    if x == 1:
        return True
    else:
        return False

In [9]:
final_df['winner'] = final_df['Position'].apply(win)

In [10]:
final_df.head()

,Election_Type,State_Name,Assembly_No,ac_no,Year,month,Poll_No,DelimID,Position,Candidate,...,TCPD_Prof_Second_Desc,ac_name,dist_name,dt_code,pc_id,pc_name,pc_no,st_code,st_name,winner
0,AE,Gujarat,11,1,2007,12,0,3,1,JAYANTILAL PARSOTTAM BHANUSHALI,...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,True
1,AE,Gujarat,11,1,2007,12,0,3,2,JADEJA NARENDRASINH MADHAVSINHJI,...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,False
2,AE,Gujarat,11,1,2007,12,0,3,3,HALEPOTRA IBRAHIM JAFAR,...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,False
3,AE,Gujarat,11,1,2007,12,0,3,4,BHAVANI HANSRAJBHAI PARBATBHAI,...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,False
4,AE,Gujarat,11,1,2007,12,0,3,5,KULINKANT BHOJRAJ SHAH (LODAYA),...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,False

In [11]:
final_df.to_csv('Final_df.csv')

In [12]:
len(final_df)

5252


# Separating final_df based on years Assembly Elections were held

In [13]:
final_df['Year'].unique()

array([2007, 2012, 2014, 2017, 2009, 2010, 2013, 2011, 2016], dtype=int64)

In [14]:
final_df_2017 = final_df[final_df['Year'] == 2017]
final_df_2012 = final_df[final_df['Year'] == 2012]
final_df_2007 = final_df[final_df['Year'] == 2007]

In [15]:
final_df_2007['ac_no'].nunique(), final_df_2012['ac_no'].nunique(), final_df_2017['ac_no'].nunique()

(182, 182, 182)

In [16]:
final_df_2007[final_df_2007['winner']]['Party'].value_counts()

BJP      116
INC       59
NCP        3
IND        2
BJNKP      1
JD(U)      1
Name: Party, dtype: int64

In [17]:
final_df_2012[final_df_2012['winner']]['Party'].value_counts()

BJP      115
INC       62
NCP        2
GPP        2
IND        1
JD(U)      1
Name: Party, dtype: int64

In [18]:
final_df_2017[final_df_2017['winner']]['Party'].value_counts()

BJP    99
INC    77
IND     3
BTP     2
NCP     1
Name: Party, dtype: int64

In [30]:
import geopandas as gd

In [31]:
sh = gd.read_file('gujarat_AC/gujarat_AC.shp')

In [32]:
sh

,ac_name,ac_no,dist_name,dt_code,pc_id,pc_name,pc_no,st_code,st_name,geometry
0,None,0,KACHCHH,01,2400,None,0,24,GUJARAT,"POLYGON ((71.28745 24.61599, 71.28326 24.60684..."
1,Vejalpur,42,AHMADABAD,07,2406,GANDHINAGAR,6,24,GUJARAT,"POLYGON ((72.52746 23.04147, 72.52856 23.02979..."
2,Jamnagar South,79,JAMNAGAR,10,2412,JAMNAGAR,12,24,GUJARAT,"POLYGON ((70.11326 22.46063, 70.12055 22.44272..."
3,Manjalpur,145,VADODARA,19,2420,VADODARA,20,24,GUJARAT,"POLYGON ((73.23656 22.29109, 73.26373 22.28369..."
4,Bhavnagar West,105,BHAVNAGAR,14,2415,BHAVNAGAR,15,24,GUJARAT,"POLYGON ((72.08070 21.81342, 72.07363 21.79259..."
...,...,...,...,...,...,...,...,...,...,...
183,Gandevi (ST),176,NAVSARI *,24,2425,NAVSARI,25,24,GUJARAT,"POLYGON ((73.12570 20.89856, 73.13476 20.89720..."
184,Dharampur,178,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT,"POLYGON ((73.01926 20.71072, 73.03361 20.70157..."
185,Pardi,180,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT,"POLYGON ((72.98923 20.51996, 72.99961 20.51646..."
186,Kaprada (ST),181,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT,"POLYGON ((73.07248 20.47422, 73.07690 20.47072..."
187,Umbergaon,182,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT,"POLYGON ((72.98017 20.28852, 72.98083 20.27431..."

In [33]:
sh.to_file("sh.geojson", driver='GeoJSON')

In [34]:
import json

In [37]:
gujarat_con = json.load(open("sh.geojson", "r"))

In [39]:
gujarat_con['features'][1]

{'type': 'Feature',
 'properties': {'ac_name': 'Vejalpur',
  'ac_no': '42',
  'dist_name': 'AHMADABAD',
  'dt_code': '07',
  'pc_id': '2406',
  'pc_name': 'GANDHINAGAR',
  'pc_no': '6',
  'st_code': '24',
  'st_name': 'GUJARAT'},
 'geometry': {'type': 'Polygon',
  'coordinates': [[[72.52745505703481, 23.04146525266232],
    [72.5285592451909, 23.029786222722816],
    [72.53673023754595, 23.01810719278331],
    [72.53363851070891, 23.009347920328683],
    [72.5387177762269, 23.005260259849855],
    [72.53430102360255, 22.998252841886153],
    [72.53739275043961, 22.99377588040934],
    [72.53032594624064, 22.988909617934546],
    [72.53783442570204, 22.97800918999101],
    [72.53915945148934, 22.976062685001093],
    [72.53849693859569, 22.956208334103934],
    [72.53032594624064, 22.952315324124097],
    [72.52149244099195, 22.957181586598892],
    [72.51022972179985, 22.976646636498067],
    [72.47511653843625, 22.970807121528313],
    [72.46915392239339, 22.97703593749605],
    [72.46738722134364, 22.994165181407325],
    [72.46407465687538, 22.99358122991035],
    [72.46562052029391, 23.0089586193307],
    [72.4894709844654, 23.02453065925004],
    [72.4894709844654, 23.028812970227857],
    [72.50559213154428, 23.03114877621576],
    [72.50802134548768, 23.03582038819156],
    [72.51950490231098, 23.034457834698618],
    [72.52745505703481, 23.04146525266232]]]}}