In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import torch.nn as nn
import torch.functional as F
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from plotly.subplots import make_subplots
import cufflinks as cf
cf.go_offline()
%matplotlib inline

In [2]:
df = pd.read_csv('GujAE.csv')
df1 = pd.read_csv('gujarat_AC.csv')

In [3]:
df1.columns

Index(['ac_name', 'ac_no', 'dist_name', 'dt_code', 'pc_id', 'pc_name', 'pc_no',
       'st_code', 'st_name'],
      dtype='object')

In [4]:
df1

,ac_name,ac_no,dist_name,dt_code,pc_id,pc_name,pc_no,st_code,st_name
0,NaN,0,KACHCHH,1,2400,NaN,0,24,GUJARAT
1,Vejalpur,42,AHMADABAD,7,2406,GANDHINAGAR,6,24,GUJARAT
2,Jamnagar South,79,JAMNAGAR,10,2412,JAMNAGAR,12,24,GUJARAT
3,Manjalpur,145,VADODARA,19,2420,VADODARA,20,24,GUJARAT
4,Bhavnagar West,105,BHAVNAGAR,14,2415,BHAVNAGAR,15,24,GUJARAT
...,...,...,...,...,...,...,...,...,...
183,Gandevi (ST),176,NAVSARI *,24,2425,NAVSARI,25,24,GUJARAT
184,Dharampur,178,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT
185,Pardi,180,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT
186,Kaprada (ST),181,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT
187,Umbergaon,182,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT

In [5]:
df.columns

Index(['Election_Type', 'State_Name', 'Assembly_No', 'Constituency_No', 'Year',
       'month', 'Poll_No', 'DelimID', 'Position', 'Candidate', 'Sex', 'Party',
       'Votes', 'Candidate_Type', 'Valid_Votes', 'Electors',
       'Constituency_Name', 'Constituency_Type', 'Sub_Region', 'N_Cand',
       'Turnout_Percentage', 'Vote_Share_Percentage', 'Deposit_Lost', 'Margin',
       'Margin_Percentage', 'ENOP', 'pid', 'Party_Type_TCPD', 'Party_ID',
       'last_poll', 'Contested', 'Last_Party', 'Last_Party_ID',
       'Last_Constituency_Name', 'Same_Constituency', 'Same_Party', 'No_Terms',
       'Turncoat', 'Incumbent', 'Recontest', 'Age', 'District_Name', 'PC_Name',
       'PC_No', 'CandID', 'MyNeta_education', 'TCPD_Prof_Main',
       'TCPD_Prof_Main_Desc', 'TCPD_Prof_Second', 'TCPD_Prof_Second_Desc'],
      dtype='object')

In [6]:
df.rename(columns={'Constituency_No':'ac_no'}, inplace=True)

In [7]:
final_df = pd.merge(df, df1, on="ac_no", how='inner')

In [8]:
final_df

,Election_Type,State_Name,Assembly_No,ac_no,Year,month,Poll_No,DelimID,Position,Candidate,...,TCPD_Prof_Second,TCPD_Prof_Second_Desc,ac_name,dist_name,dt_code,pc_id,pc_name,pc_no,st_code,st_name
0,AE,Gujarat,11,1,2007,12,0,3,1,JAYANTILAL PARSOTTAM BHANUSHALI,...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
1,AE,Gujarat,11,1,2007,12,0,3,2,JADEJA NARENDRASINH MADHAVSINHJI,...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
2,AE,Gujarat,11,1,2007,12,0,3,3,HALEPOTRA IBRAHIM JAFAR,...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
3,AE,Gujarat,11,1,2007,12,0,3,4,BHAVANI HANSRAJBHAI PARBATBHAI,...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
4,AE,Gujarat,11,1,2007,12,0,3,5,KULINKANT BHOJRAJ SHAH (LODAYA),...,NaN,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5247,AE,Gujarat,13,182,2017,12,0,4,4,BOCHAL HASMUKHBHAI RAMANBHAI,...,Agriculture,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT
5248,AE,Gujarat,13,182,2017,12,0,4,5,SHAILESHBHAI UKADBHAI DABHADIA,...,NaN,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT
5249,AE,Gujarat,13,182,2017,12,0,4,6,NARESHBHAI UKKADBHAI OZARIYA,...,NaN,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT
5250,AE,Gujarat,13,182,2017,12,0,4,7,VADIYA LAXMANBHAI CHHAGANBHAI,...,NaN,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT
5251,AE,Gujarat,13,182,2017,12,0,4,8,GOVINDBHAI VESTABHAI PATEL,...,NaN,NaN,Umbergaon,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT

In [9]:
def win(x):
    if x == 1:
        return True
    else:
        return False

In [10]:
final_df['winner'] = final_df['Position'].apply(win)

In [11]:
final_df.head()

,Election_Type,State_Name,Assembly_No,ac_no,Year,month,Poll_No,DelimID,Position,Candidate,...,TCPD_Prof_Second_Desc,ac_name,dist_name,dt_code,pc_id,pc_name,pc_no,st_code,st_name,winner
0,AE,Gujarat,11,1,2007,12,0,3,1,JAYANTILAL PARSOTTAM BHANUSHALI,...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,True
1,AE,Gujarat,11,1,2007,12,0,3,2,JADEJA NARENDRASINH MADHAVSINHJI,...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,False
2,AE,Gujarat,11,1,2007,12,0,3,3,HALEPOTRA IBRAHIM JAFAR,...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,False
3,AE,Gujarat,11,1,2007,12,0,3,4,BHAVANI HANSRAJBHAI PARBATBHAI,...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,False
4,AE,Gujarat,11,1,2007,12,0,3,5,KULINKANT BHOJRAJ SHAH (LODAYA),...,NaN,Abdasa,KACHCHH,1,2401,KACHCHH (SC),1,24,GUJARAT,False

In [12]:
final_df.to_csv('Final_df.csv')

In [13]:
len(final_df)

5252


# Separating final_df based on years Assembly Elections were held

In [14]:
final_df['Year'].unique()

array([2007, 2012, 2014, 2017, 2009, 2010, 2013, 2011, 2016], dtype=int64)

In [15]:
final_df_2017 = final_df[final_df['Year'] == 2017]
final_df_2012 = final_df[final_df['Year'] == 2012]
final_df_2007 = final_df[final_df['Year'] == 2007]

In [16]:
final_df_2007['ac_no'].nunique(), final_df_2012['ac_no'].nunique(), final_df_2017['ac_no'].nunique()

(182, 182, 182)

In [17]:
final_df_2007[final_df_2007['winner']]['Party'].value_counts()

BJP      116
INC       59
NCP        3
IND        2
BJNKP      1
JD(U)      1
Name: Party, dtype: int64

In [18]:
final_df_2012[final_df_2012['winner']]['Party'].value_counts()

BJP      115
INC       62
NCP        2
GPP        2
IND        1
JD(U)      1
Name: Party, dtype: int64

In [19]:
final_df_2017[final_df_2017['winner']]['Party'].value_counts()

BJP    99
INC    77
IND     3
BTP     2
NCP     1
Name: Party, dtype: int64

In [20]:
import geopandas as gd

In [21]:
sh = gd.read_file('gujarat_AC/gujarat_AC.shp')

In [22]:
sh

,ac_name,ac_no,dist_name,dt_code,pc_id,pc_name,pc_no,st_code,st_name,geometry
0,None,0,KACHCHH,01,2400,None,0,24,GUJARAT,"POLYGON ((71.28745 24.61599, 71.28326 24.60684..."
1,Vejalpur,42,AHMADABAD,07,2406,GANDHINAGAR,6,24,GUJARAT,"POLYGON ((72.52746 23.04147, 72.52856 23.02979..."
2,Jamnagar South,79,JAMNAGAR,10,2412,JAMNAGAR,12,24,GUJARAT,"POLYGON ((70.11326 22.46063, 70.12055 22.44272..."
3,Manjalpur,145,VADODARA,19,2420,VADODARA,20,24,GUJARAT,"POLYGON ((73.23656 22.29109, 73.26373 22.28369..."
4,Bhavnagar West,105,BHAVNAGAR,14,2415,BHAVNAGAR,15,24,GUJARAT,"POLYGON ((72.08070 21.81342, 72.07363 21.79259..."
...,...,...,...,...,...,...,...,...,...,...
183,Gandevi (ST),176,NAVSARI *,24,2425,NAVSARI,25,24,GUJARAT,"POLYGON ((73.12570 20.89856, 73.13476 20.89720..."
184,Dharampur,178,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT,"POLYGON ((73.01926 20.71072, 73.03361 20.70157..."
185,Pardi,180,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT,"POLYGON ((72.98923 20.51996, 72.99961 20.51646..."
186,Kaprada (ST),181,VALSAD,25,2426,VALSAD (ST),26,24,GUJARAT,"POLYGON ((73.07248 20.47422, 73.07690 20.47072..."
187,Umbergaon,182,NAVSARI *,24,2426,VALSAD (ST),26,24,GUJARAT,"POLYGON ((72.98017 20.28852, 72.98083 20.27431..."

In [23]:
sh.to_file("sh.geojson", driver='GeoJSON')

In [24]:
import json

In [25]:
gujarat_con = json.load(open("sh.geojson", "r"))

In [26]:
gujarat_con['features'][0].keys()

dict_keys(['type', 'properties', 'geometry'])

In [34]:
import plotly.express as px

In [35]:
import plotly.io as pio

In [41]:
pio.renderers.default = 'firefox'

In [42]:
final_df_2017_winner = final_df_2017[final_df_2017['winner'] == True]

In [43]:
len(final_df_2017_winner)

182

In [45]:
fig =px.choropleth(final_df_2017_winner, locations='ac_no', geojson=gujarat_con, color='Party', scope='asia')
fig.update_geos(fitbounds=locations, visible=False)
fig.show()

NameError: name 'locations' is not defined

In [49]:
state_id_map = {}
for feature in gujarat_con['features']:
    feature['id'] = feature['properties']['ac_no']
    state_id_map[feature['properties']['ac_name']] = feature['id']

In [50]:
gujarat_con['features'][0]['properties']

{'ac_name': None,
 'ac_no': '0',
 'dist_name': 'KACHCHH',
 'dt_code': '01',
 'pc_id': '2400',
 'pc_name': None,
 'pc_no': '0',
 'st_code': '24',
 'st_name': 'GUJARAT'}

In [51]:
state_id_map

{None: '0',
 'Vejalpur': '42',
 'Jamnagar South': '79',
 'Manjalpur': '145',
 'Bhavnagar West': '105',
 'Vansda (ST)': '177',
 'Rajkot South': '70',
 'Kankrej': '15',
 'Bhuj': '3',
 'Amraiwadi': '50',
 'Kheralu': '20',
 'Visnagar': '22',
 'Mansa': '37',
 'Kadi (SC)': '24',
 'Surat East': '159',
 'Lunawada': '122',
 'Gandhinagar(North)': '36',
 'Vatva': '43',
 'Kapadvanj': '120',
 'Ghatlodia': '41',
 'Jamalpur-Khadia': '52',
 'Morva Hadaf': '125',
 'Jhalod (ST)': '130',
 'Tankara': '66',
 'Savli': '135',
 'Anand': '112',
 'Rajkot West': '69',
 'Surat West': '167',
 'Sayajigunj': '142',
 'Padra': '146',
 'Jambusar': '150',
 'Porbandar': '83',
 'Bharuch': '153',
 'Karanj': '162',
 'Ankleshwar': '154',
 'Somnath': '90',
 'Naroda': '47',
 'Bardoli (SC)': '169',
 'Tharad': '8',
 'Deesa': '13',
 'Varachha Road': '161',
 'Vav': '7',
 'Majura': '165',
 'Unjha': '21',
 'Udhna': '164',
 'Limbayat': '163',
 'Dhanera': '9',
 'Surat North': '160',
 'Danta (ST)': '10',
 'Deodar': '14',
 'Khedbrahma(ST)': '29',
 'Katargam': '166',
 'Palanpur': '12',
 'Vijapur': '26',
 'Vadgam (SC)': '11',
 'Sidhpur': '19',
 'Ellisbridge': '44',
 'Radhanpur': '16',
 'Abdasa': '1',
 'Naranpura': '45',
 'Patan': '18',
 'Sabarmati': '55',
 'Chanasma': '17',
 'Bhiloda (ST)': '30',
 'Rapar': '6',
 'Idar (SC)': '28',
 'Mahesana': '25',
 'Becharaji': '23',
 'Himatnagar': '27',
 'Modasa': '31',
 'Gandhidham(SC)': '5',
 'Anjar': '4',
 'Prantij': '33',
 'Gandhinagar(South)': '35',
 'Dasada (SC)': '60',
 'Viramgam': '39',
 'Asarwa': '56',
 'Bayad': '32',
 'Dahegam': '34',
 'Dariyapur': '51',
 'Mandvi': '2',
 'Santrampur': '123',
 'Dhrangadhra': '64',
 'Morbi': '65',
 'Fatepura (ST)': '129',
 'Danilimda': '54',
 'Thakkar Bapanagar': '48',
 'Kalol': '127',
 'Nikol': '46',
 'Balasinor': '121',
 'Bapunagar': '49',
 'Sanand': '40',
 'Wadhwan': '62',
 'Maninagar': '53',
 'Daskroi': '57',
 'Kalavad (SC)': '76',
 'Wankaner': '67',
 'Jamnagar': '77',
 'Shehra': '124',
 'Limkheda (ST)': '131',
 'Chotila': '63',
 'Mehmedabad': '117',
 'Thasra': '119',
 'Dholka': '58',
 'Dahod (ST)': '132',
 'Mahudha': '118',
 'Godhra': '126',
 'Matar': '115',
 'Devgadhbaria': '134',
 'Limbdi': '61',
 'Dwarka': '82',
 'Garbada (ST)': '133',
 'Umreth': '111',
 'Nadiad': '116',
 'Jamnagar North': '78',
 'Khambhalia': '81',
 'Sojitra': '114',
 'Jamjodhpur': '80',
 'Petlad': '113',
 'Chhota Udaipur (ST': '137',
 'Dhandhuka': '59',
 'Anklav': '110',
 'Halol': '128',
 'Khambhat': '108',
 'Rajkot Rural(SC)': '71',
 'Vaghodia': '136',
 'Borsad': '109',
 'Botad': '107',
 'Rajkot East': '68',
 'Jasdan': '72',
 'Mahuva (ST)': '170',
 'Sankheda(ST)': '139',
 'Vadodara City(SC)': '141',
 'Raopura': '144',
 'Akota': '143',
 'Jetpur (ST)': '138',
 'Choryasi': '168',
 'Dabhoi': '140',
 'Gondal': '73',
 'Gadhada (SC)': '106',
 'Jetpur': '74',
 'Dhoraji': '75',
 'Bhavnagar Rural': '103',
 'Karjan': '147',
 'Lathi': '96',
 'Kutiyana': '84',
 'Nandod (ST)': '148',
 'Amreli': '95',
 'Vagra': '151',
 'Jhagadia (ST)': '152',
 'Manavadar': '85',
 'Bhavnagar East': '104',
 'Palitana': '102',
 'Junagadh': '86',
 'Kodinar (SC)': '92',
 'Visavadar': '87',
 'Gariadhar': '101',
 'Keshod': '88',
 'Dhari': '94',
 'Savarkundla': '97',
 'Dediapada(ST)': '149',
 'Valsad': '179',
 'Talaja': '100',
 'Mangrol (ST)': '156',
 'Talala': '91',
 'Nizar (ST)': '172',
 'Olpad': '155',
 'Mandvi (ST)': '157',
 'Mangrol': '89',
 'Kamrej': '158',
 'Una': '93',
 'Mahuva': '99',
 'Rajula': '98',
 'Vyara (ST)': '171',
 'Jalalpore': '174',
 'Navsari': '175',
 'Dangs (ST)': '173',
 'Gandevi (ST)': '176',
 'Dharampur': '178',
 'Pardi': '180',
 'Kaprada (ST)': '181',
 'Umbergaon': '182'}